# -*- coding: utf-8 -*-
"""Seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OpUYGubfm5-UgPmOp3zWZKa6WjLrKuiV
"""

# Matplotlib

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

x = np.linspace(0, 10, 1000)
plt.plot(x, np.sin(x), x, np.cos(x))
plt.show()

plt.plot(x, np.sin(x), x, np.cos(x))

# Seaborn
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

sns.set()

x = np.linspace(0, 10, 1000)
plt.plot(x, np.sin(x), x, np.cos(x))
plt.show()

df = sns.load_dataset("tips")
df.head()

df.tail()

sns.relplot(x = "total_bill", y = "tip", data = df, kind = "scatter")
plt.show()

sns.relplot(x = "total_bill", y = "tip", data = df, kind = "line")
plt.show()

# Parameters -
# • x, y
# • data
# • hue: It separtes the colour of dots with their types.
# • size
# • col: It can help to have different sex graphs.
# • style: They are used for showing differnt style of points.

sns.relplot(x = "total_bill", y = "tip", data = df, kind = "scatter", hue = "day")
plt.show()